spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data-source:
    url: jdbc:postgresql://localhost:5432/store
    username: store
    password: asdqwe123
  flyway:
    baseline-on-migrate: true



